### ISSUE TITLE
Missing function?

### ISSUE THREAD

**Issue by rlogiacco** [arpruss/ADCTouchSensor#2]
While trying to compile for STM32 architecture I got a compilation error at https://github.com/arpruss/ADCTouchSensor/blob/b0ebd814f01e05ce39d4d53f2ad145412f8c3a92/src/ADCTouchSensor.cpp#L79

```
ADCTouchSensor\0.0.9\src\ADCTouchSensor.cpp: In member function 'int ADCTouchSensor::readRaw(unsigned int)':
ADCTouchSensor\0.0.9\src\ADCTouchSensor.cpp:79:20: error: 'ground' was not declared in this scope
             ground();
                    ^
```

Am I missing something?

**Comment by 203Null** [comment]
It only works on f103c, you can manually select the grounded pin for other stm32, or find a grounded pin of  the ADC.

**Comment by ChoCho59** [comment]
I face the same problem. 

I don't know how to "manually select the grounded pin for other stm32, or find a grounded pin of the ADC"  !

**Comment by arpruss** [comment]
I fixed the bug in the code.

In the constructor, you need to use sacrificialPin to specify an analog pin that you won't use for touch sensing or anything else but which will be used for grounding the internal ADC capacitor. You then leave this pin floating in your project.
