### ISSUE TITLE
Need help for adding more button

### ISSUE THREAD

**Issue by 2ndtr2n** [arpruss/ADCTouchSensor#3]
I wanna make 16 buttons, how can i add the code?

**Comment by arpruss** [comment]
On what hardware?

**Comment by 2ndtr2n** [comment]
I'll build the midi fighter using stm32 : https://store.djtechtools.com/products/midi-fighter-3d
Hope you support me

**Comment by arpruss** [comment]
The stm32f1 doesn't have enough ADCs for 16 capacitive buttons. You'll want to go with hardware buttons.
